apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolenotifications.console.openshift.io
  annotations:
    displayName: ConsoleNotification
    description: Extension for configuring openshift web console notifications.
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
  - name: v1
    served: true
    storage: true
  names:
    plural: consolenotifications
    singular: consolenotification
    kind: ConsoleNotification
    listKind: ConsoleNotificationList
  additionalPrinterColumns:
  - name: Text
    type: string
    JSONPath: .spec.text
  - name: Location
    type: string
    JSONPath: .spec.location
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console notification spec
          required:
          - text
          - location
          properties:
            text:
              type: string
              description: Text of the notification
            location:
              type: string
              description: The location of the notification (BannerTop, BannerBottom, BannerTopBottom)
              pattern: '^(BannerTop|BannerBottom|BannerTopBottom)$'
            link:
              type: object
              description: Object that holds notification link details
              required:
              - href
              - text
              properties:
                text:
                  type: string
                  description: Text of the link
                href:
                  type: string
                  description: Absolute secure URL for the link (must use https)
                  pattern: '^https://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$'
            backgroundColor:
              type: string
              description:  The background color for the notification as CSS data type color
            color:
              type: string
              description:  The color of the text for the notification as CSS data type color
