apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleexternalloglinks.console.openshift.io
  annotations:
    displayName: ConsoleExternalLogLinks
    description: ConsoleExternalLogLink is an extension for customizing OpenShift web console log links.
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
  - name: v1
    served: true
    storage: true
  names:
    plural: consoleexternalloglinks
    singular: consoleexternalloglink
    kind: ConsoleExternalLogLink
    listKind: ConsoleExternalLogLinkList
  additionalPrinterColumns:
  - name: Text
    type: string
    JSONPath: .spec.text
  - name: HrefTemplate
    type: string
    JSONPath: .spec.hrefTemplate
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: >-
            ConsoleExternalLogLinkSpec is the desired log link configuration.
            The log link will appear on the logs tab of the pod details page.
          required:
          - text
          - hrefTemplate
          properties:
            text:
              type: string
              description: text is the display text for the link
            hrefTemplate:
              type: string
              description: |-
                hrefTemplate is an absolute secure URL (must use https) for the log link including variables to be replaced. Variables are specified in the URL with the format ${variableName}, for instance, ${containerName} and will be replaced with the corresponding values from the resource. Resource is a pod.
                Supported variables are
                  * ${resourceName} - name of the resource which containes the logs
                  * ${resourceUID} - UID of the resource which contains the logs
                    * e.g. `11111111-2222-3333-4444-555555555555`
                  * ${containerName} - name of the resource's container that contains the logs
                  * ${resourceNamespace} - namespace of the resource that contains the logs
                  * ${podLabels} - JSON representation of labels matching the pod with the logs
                    * e.g. `{"key1":"value1","key2":"value2"}`
                e.g., https://example.com/logs?resourceName=${resourceName}&containerName=${containerName}&resourceNamespace=${resourceNamespace}&podLabels=${podLabels}
              pattern: '^https://'
            namespaceFilter:
              type: string
              description: >-
                  namespaceFilter is a regular expression used to restrict a log link to a
                  matching set of namespaces (e.g., `openshift-`). If not specified, links will
                  be displayed for all the namespaces.
