apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleclidownloads.console.openshift.io
  annotations:
    displayName: ConsoleCLIDownload
    description: Extension for configuring openshift web console command line interface (CLI) downloads.
spec:
  group: console.openshift.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: consoleclidownloads
    singular: consoleclidownload
    kind: ConsoleCLIDownload
    listKind: ConsoleCLIDownloadList
  additionalPrinterColumns:
  - name: Display name
    type: string
    JSONPath: .spec.displayName
  - name: Age
    type: string
    JSONPath: .metadata.creationTimestamp
  - name: Description
    type: string
    JSONPath: .spec.description
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console CLI download spec
          required:
          - displayName
          - description
          - link
          properties:
            displayName:
              type: string
              description: Display name of the CLI download
            description:
              type: string
              description: Description of the CLI download (can include markdown)
            link:
              type: object
              description: Object that holds CLI download link details
              required:
              - href
              properties:
                text:
                  type: string
                  description: Text of the link
                href:
                  type: string
                  description: Absolute secure URL for the link (must use https)
                  pattern: '^https://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$'
