# any logged-in user authenticated through the
# console needs READONLY access to these resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-extensions
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  - consoleclidownloads
  - consolenotificationbanners
  verbs:
  - get
  - list
  - watch
