kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
