apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-console-operator
  name: console-operator-config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  controller-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
    leaderElection:
      namespace: openshift-console-operator
    servingInfo:
      bindNetwork: "tcp"
