apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-operator
  namespace: openshift-console-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: openshift-console
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
