apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  managementState: Managed
  authentication:
    # the logout redirect must be a valid URI that starts with http(s)
    # valid examples: http://localhost:8080/logout.html, https://www.redhat.com/log/out/
    logoutRedirect: "https://www.redhat.com/i/should/logout"
  customization:
    brand: okd
    # the documentation base must be a valid URI that starts with http(s) AND it must have a trailing slash
    # the trailing slash is required because additional values will be appended
    # valid examples: https://localhost:9999/docs/, http://192.168.1.5:3000/doc/location/
    documentationBaseURL: "https://www.redhat.com/someplace/for/docs/"
