# oc create this file to create a bunch of resources
# simply to see if the informers all fire
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-bar-baz
  namespace: openshift-console
---
kind: Service
apiVersion: v1
metadata:
  name: foo-bar-baz
  namespace: openshift-console
---
kind: Route
apiVersion: v1
metadata:
  name: foo-bar-baz
  namespace: openshift-console
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: foo-bar-baz
  namespace: openshift-console
---
kind: Secret
apiVersion: v1
metadata:
  name: foo-bar-baz
  namespace: openshift-console
---
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: foo-bar-baz
  # oauth is cluster scoped
